apiVersion: v1
kind: Namespace
metadata:
  name:  ingress
  
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx
  namespace: kube-system
spec:
  targetNamespace: ingress
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx

  valuesContent: |-
    controller:
      replicaCount: 1
      updateStrategy:
        type: "RollingUpdate"
        rollingUpdate:
          maxUnavailable: 1
      hostPort:
        enabled: true
      terminationGracePeriodSeconds: 0
      service:
        type: "NodePort"
      watchIngressWithoutClass: true
      nodeSelector:
        ingress-ready: "true"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          effect: "NoSchedule"
      publishService:
        enabled: false
      extraArgs:
        publish-status-address: "localhost"
        default-ssl-certificate: "default/ssl"
      metrics:
        enabled: true
        service:
          annotations: 
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"