apiVersion: v1
kind: Namespace
metadata:
  name:  monitoring

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: kube-system
spec:
  targetNamespace: monitoring
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus

  valuesContent: |-

    serviceAccounts:
      alertmanager:
        create: false
    alertmanager:
      enabled: false
    configmapReload:
      prometheus:
        enabled: true
      alertmanager:
        enabled: false
    server:
      enabled: true
      ingress:
        enabled: true
        hosts: 
          - prom.${DOMAIN}
        tls: 
          - hosts:
              - prom.${DOMAIN}
      dnsConfig: 
        nameservers:
          - "1.1.1.1"
          - "8.8.8.8"
      retention: "1d"